[package]
name = "libhmsbeagle-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"
